### ISSUE TITLE
MfaFido2SignInFidoController constructor

### ISSUE THREAD

**Issue by nicowitteman** [damienbod/AspNetCoreIdentityFido2Mfa#10]
Hi Damien, the MfaFido2SignInFidoController constructor contains this statement twice: "_userManager = userManager;" while it is not even used at all. 
And while we're at it, wouldn't it be logical to include the result of the await _signInManager.TwoFactorSignInAsync("FIDO2", string.Empty, false, false) in the return value of the MakeAssertion call, or is this covered by the exception handler?
Nico

**Comment by damienbod** [comment]
Thanks, I must clean thi part up, thanks for reporting. 

I'll fix this in the next few days. Or if you want to do a PR, would also be good.

Greetings Damien

**Comment by nicowitteman** [comment]
I'll leave it to you, if you don't mind.

**Comment by damienbod** [comment]
fixed, thanks for reporting
