### ISSUE TITLE
Exception handling in PwFido2SignInController.cs

### ISSUE THREAD

**Issue by nicowitteman** [damienbod/AspNetCoreIdentityFido2Mfa#12]
Hi Damien, I propose to move the "throw new ArgumentException("Username was not registered");" a few lines up: instead of checking the existence of the user, check the existence of the identityUser, for when that is empty, the new FidoUser will throw an uncaught exception. Suggestion: if (identityUser == null) throw new ArgumentException("Username was not registered");

**Comment by damienbod** [comment]
I will add this when updating to version 3 of the FIDO2 lib

**Comment by nicowitteman** [comment]
I cerated pull request #56
