### ISSUE TITLE
Failed to read the 'publicKey' property from 'CredentialCreationOptions'

### ISSUE THREAD

**Issue by gerrymcjr** [damienbod/AspNetCoreIdentityFido2Mfa#16]
Hi damien, i am trying out the mfa implementation but i am facing this error on registration `exception:TypeError: Failed to execute 'create' on 'CredentialsContainer': Failed to read the 'publicKey' property from 'CredentialCreationOptions': Failed to read the 'attestation' property from 'PublicKeyCredentialCreationOptions': The provided value '0' is not a valid enum value of type AttestationConveyancePreference.` on mfa.register.js line 80

i noticed these codes on MfaFidoRegisterController `var items = await _fido2Storage.GetCredentialsByUsername(identityUser.UserName);
                var existingKeys = new List<PublicKeyCredentialDescriptor>();
                foreach (var publicKeyCredentialDescriptor in items)
                {
                    existingKeys.Add(publicKeyCredentialDescriptor.Descriptor);
                }`
does this have anything to do with the error above?

* i am using a copy of an existing AspNetIdentity Database and added the FidoStoredCredential table

**Comment by gerrymcjr** [comment]
My fault the AspNetIdentity is configured to use a normal username instead of email

**Comment by damienbod** [comment]
glad it's working

Greetings Damien
