### ISSUE TITLE
Update to FIDO2 3 beta when ready

### ISSUE THREAD

**Issue by vanillajonathan** [damienbod/AspNetCoreIdentityFido2Mfa#19]
Consider upstreaming parts of this to the ASP.NET Core project.

Particularly the `FidoStoredCredential` model and the changes to `ApplicationDbContextModelSnapshot.cs`.

**Comment by damienbod** [comment]
Updated, thanks for the issue

**Comment by damienbod** [comment]
https://github.com/passwordless-lib/fido2-net-lib/issues/264#issuecomment-1169971238

**Comment by vanillajonathan** [comment]
What do you think of maybe upstreaming to ASP.NET Core?
The `FidoStoredCredentials` class and the changes to `ApplicationDbContextModelSnapshot.cs`.

**Comment by damienbod** [comment]
I will ask again, but ASP.NET Core Identity will not want external dependencies in their code base, which makes sense, so I cannot see this happening.

**Comment by vanillajonathan** [comment]
Hmm, true the `PublicKeyCredentialDescriptor` is an external dependency, I didn't think about that one, but since that one is `NotMapped` maybe it could be moved out from the class. Then just upstream things that have no external dependencies, I was mostly thinking about the `FidoStoredCredentials` class.
