### ISSUE TITLE
returnUrl is not handled correctly in case of FIDO2 login

### ISSUE THREAD

**Issue by ChristianRiedl** [damienbod/AspNetCoreIdentityFido2Mfa#31]
After login redirection is always done to the root page.

The reason is that in the LoginFido2Mfa page the **ReturnUrl** is not stored.

It can be fixed applying the BindProperty attribute (with GET)  in the page model.

    [BindProperty(SupportsGet=true)]
    public bool RememberMe { get; set; }

    [BindProperty(SupportsGet = true)]
    public string ReturnUrl { get; set; }

**Comment by damienbod** [comment]
fixed https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/pull/33
