### ISSUE TITLE
Deployment in subfolder breaks calls to back-end

### ISSUE THREAD

**Issue by nicowitteman** [damienbod/AspNetCoreIdentityFido2Mfa#49]
In passwordless.login.js and passwordless.register.js, calls to back-end like "/pwmakeAssertion" don't work if the application is deployed in a subfolder like "https://somehost.com/myapplication/".
I suggest to 
a) add this line to Login.cshtml and Register.cshtml:
`<input type="hidden" id="BasePath" name="BasePath" value="@Url.Content("~")">`
and 
b) add a helper function like
```
function getFolder() {
    var dir = "";
    try {
        dir = document.getElementById('BasePath').value;
    } catch (e) {
    }
    return dir;
}
```
and then call 
`fetch(getFolder() + "/pwmakeAssertion" ....`

**Comment by damienbod** [comment]
@nicowitteman  Thanks for the feedback! Would you like to do a PR? If not I will update

Greetings Damien

**Comment by nicowitteman** [comment]
I realized this does not work as I hoped if the application is deployed in the root, Instead, pass the base path from login.cshtml like so:                 
`<input type="hidden" id="BasePath" name="BasePath" value="@Url.Content("~")">`
and use this code for getFolder:
```
function getFolder() {
    var dir = "";
    try {
        dir = document.getElementById('BasePath').value;
    } catch (e) {
    }
    return dir;
}
```

**Comment by nicowitteman** [comment]
I prepared a PR, waiting for merge of https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/pull/56
