### ISSUE TITLE
userHandle null

### ISSUE THREAD

**Issue by nicowitteman** [damienbod/AspNetCoreIdentityFido2Mfa#50]
In passwordless.login.js, in verifyAssertionWithServer, if assertedCredential.response.userHandle  is null, still userHandle in data.response is set to "" by coerceToBase64Url(userHandle). Suggest to add check on userHandle.length like so:
`userHandle: userHandle !== null && userHandle.length > 0 ? coerceToBase64Url(userHandle) : null,`

**Comment by damienbod** [comment]
@nicowitteman  Thanks for the feedback! Would you like to do a PR? If not I will update

Greetings Damien

**Comment by nicowitteman** [comment]
I prepared a PR, waiting for merge of #56
